# Generated by Django 3.2.7 on 2021-11-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('valor_horac', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('RG', models.CharField(max_length=12)),
                ('CPF', models.CharField(max_length=14)),
                ('celular', models.CharField(blank=True, max_length=14, null=True)),
                ('rua', models.CharField(max_length=100)),
                ('numeroCasa', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=10)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.funcao')),
            ],
        ),
    ]
