# Generated by Django 3.2.7 on 2021-11-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('manu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='fk_codEletrista',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.funcionario'),
        ),
    ]
